" => General
" Sets how many lines of history VIM has to remember
set history=500
set viminfo+=:500

" Enable filetype plugins
filetype plugin on
filetype indent on

" Load all plugins now.
packloadall

" With a map leader it's possible to do extra key combinations
let mapleader = ","

" Python shortcut
autocmd FileType python map <buffer> <F9> <esc>:w<CR>:exec '!python3' shellescape(@%, 1)<CR>

" Javascript shortcut
autocmd FileType javascript map <buffer> <F9> <esc>:w<CR>:exec '!node' shellescape(@%, 1)<CR>

" => VIM user interface
" Set number
set relativenumber

" Set numberwidth
set numberwidth=3
set nostartofline

" Set 5 lines to the cursor
set sidescroll=5
set scrolloff=5

" Turn on the Wild menu
set wildmenu
set wildmode=longest,full

" Always show current position
set ruler

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set completeopt=menu,preview

set clipboard=

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Save searches
set viminfo+=/200

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Terminal window title
set title
set titlestring=%t
set titleold=


" => Colors and Fonts
" Enable syntax highlighting
syntax enable
set background=dark
let g:solarized_termtrans=1
colorscheme solarized

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Linting
let g:ale_set_signs = 0
let g:ale_lint_delay = 0
let g:ale_set_highlights = 1

highlight ALEError ctermbg=none ctermfg=red cterm=underline
highlight ALEWarning ctermbg=none ctermfg=red cterm=underline

" => Fzf
" Adding the directory to runtimepath
set rtp+=~/.fzf

" Empty value to disable preview window altogether
let g:fzf_preview_window = ''

" Set history
let g:fzf_history_dir = '~/.local/share/fzf-history'

" Open files in horizontal split
nnoremap <silent> <Leader>s :call fzf#run({
\   'down': '40%',
\   'sink': 'botright split' })<CR>

" Open files in vertical horizontal split
nnoremap <silent> <Leader>v :call fzf#run({
\   'right': winwidth('.') / 2,
\   'sink':  'vertical botright split' })<CR>


" => Cursor
" Ps = 0  -> blinking block.
" Ps = 1  -> blinking block (default).
" Ps = 2  -> steady block.
" Ps = 3  -> blinking underline.
" Ps = 4  -> steady underline.
" Ps = 5  -> blinking bar (xterm).
" Ps = 6  -> steady bar (xterm).

if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[2 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' | 
    \   silent execute '!echo -ne "\e[6 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[6 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif

autocmd VimEnter * silent exec "! echo -ne '\e[2 q'"
autocmd VimLeave * silent exec "! echo -ne '\e[6 q'"

" => Text, tab and indent related
" Use spaces instead of tabs
set expandtab

" No smartindent
set nosmartindent

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=8
set softtabstop=-1

" Linebreak on 60 characters
set tw=60 cc=60
set nojoinspaces
set formatoptions=cloqr

set noai " Don't auto indent
set nowrap "Don't wrap lines


" => Moving around, tabs, windows and buffers
" Map <Space> to / (search) and Ctrl-<Space> to ? (backwards search)
map <space> /
map <C-space> ?

" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>tc :tabclose<cr>
set splitbelow splitright


" => Swap
" Save swap file in ~/.vim/swap/
set directory=~/.vim/swap/


" => Status line
" Always show the status line
set laststatus=2

" Filename [Help][-][RO]
set statusline=\ \ \ %<%f\ %h%m%r

" Line, col
set statusline+=%=%(%l,%c%V%)

" Showcmd
set esckeys
set notimeout ttimeout ttimeoutlen=0
set showcmd

set exrc secure
