" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8
scriptencoding utf-8

" Sets how many lines of history VIM has to remember
set history=500

set nocompatible
packloadall

" Terminal window title
set title
set titlestring=%t

" Disable match {} () []
set noshowmatch
set nosm
let g:loaded_matchparen=1

" Unhighlight search results
nmap <silent> <unique> <Leader>l :nohlsearch<CR>

" Run Python shortcut
autocmd FileType python map <buffer> <F1> <esc>:w<CR>:exec '!python3' shellescape(@%, 1)<CR>

" Run Node shortcut
autocmd FileType javascript map <buffer> <F1> <esc>:w<CR>:exec '!node' shellescape(@%, 1)<CR>

" Run GCC shortcut
autocmd Filetype c map <buffer> <F1> <esc>:w<CR>:exec '!gcc '.shellescape('%').' -o '.shellescape('%:r').' && ./'.shellescape('%:r')<CR>

" Spell check
" set spell
" nmap <silent> <unique> <Leader>m :highlight SpellBad ctermbg=none ctermfg=red cterm=underline<CR>

" Vimgrep
command -nargs=+ Grep :vimgrep "<args>" **/* | copen

" Turn on the Wild menu
set wildmenu

" Set number
set relativenumber

"" Line on 80
set tw=80 cc=80

" Enable filetype plugins
filetype plugin on
filetype indent on

" Set 5 lines to the cursor - when moving vertically using j/k
set so=5

"Always show current position
set ruler

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Enable syntax highlighting
syntax enable
set background=dark
let g:solarized_termtrans=1
colorscheme solarized

" Use spaces instead of tabs
set expandtab

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>tc :tabclose<cr>

" Always show the status line
set laststatus=2

" Fzf
set rtp+=~/.fzf/

" Open files in current directory in new tab
nmap <unique> <Leader>b :call fzf#run({'sink': 'tabedit', 'down': '40%'})<CR>

" Open files in current directory
nmap <unique> <C-P> :FZF <CR>

" ALE
let g:ale_set_signs = 0
let g:ale_lint_delay = 0
let g:ale_set_highlights = 1
let g:ale_lint_on_text_changed = 'always'

" Underline the ALE with red color
highlight ALEError ctermbg=none ctermfg=red cterm=underline
highlight ALEWarning ctermbg=none ctermfg=red cterm=underline

let &t_SI.="\e[6 q" "SI = INSERT mode
let &t_SR.="\e[4 q" "SR = REPLACE mode
let &t_EI.="\e[2 q" "EI = NORMAL mode

" Everything from here to below is from -> @strager: https://github.com/strager
" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=8
set softtabstop=-1

" Dislpay
set list
set listchars=
set listchars+=precedes:<,extends:>
set listchars+=tab:⇥\ 

set noai "Do not auto indent
set nowrap "Do not wrap lines
set nosmartindent
set nojoinspaces
set numberwidth=3
set nostartofline
set formatoptions=cloqr

" Configure backspace
set backspace=indent,eol,start
set completeopt=menu,preview

" Change tab in vim
let s:i = 1
while s:i <= 10
  execute printf(
    \ 'nnoremap <unique> <Leader>%d :%dtabnext<CR>',
    \ s:i == 10 ? 0 : s:i,
    \ s:i,
  \ )
  let s:i += 1
endwhile

"Quick-lint-js
set rtp+=/usr/share/vim/addons

" Save swap file in ~/.vim/swap/
set directory=~/.vim/swap/

" Filename [Help][-][RO]
set statusline=\ \ \ %<%f\ %h%m%r

" Line, col
set statusline+=%=%(%l,%c%V%)

" Handle <ESC> immediately in insert mode
set esckeys
set notimeout ttimeout ttimeoutlen=0
set showcmd

set exrc secure
