sudo apt install flake8
sudo apt install cmake
sudo apt install ninja-build
sudo apt install pylint
sudo apt install htop
sudo apt install zsh
sudo apt install tree
sudo apt install xclip
sudo apt install ncdu
sudo apt install git
sudo apt install python3-pygame
sudo apt install python3-tk
sudo apt install build-essential
sudo apt install pngcrush
sudo apt install python3-venv python3-pip
sudo apt install vim
sudo apt install libpq-dev
sudo apt install vim-gtk
sudo apt install sqlite3
sudo apt install python3
