fpath=(~/dotfiles/zsh/jan "${fpath[@]}")
autoload -Uk strager_prompt_cwd

source $HOME/dotfiles/zsh/aliases
source ~/dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

export EDITOR=vim
export PATH=~/Downloads/Discord:$PATH
export PATH=~/Downloads/node-v12.18.3-linux-x64/bin:$PATH
export PATH=~/Downloads/pycharm-community-2020.2.1/bin:$PATH

# => Prompt
# Credit Strager https://github.com/strager/dotfiles
setopt prompt_subst
PROMPT=
# Current directory.
PROMPT="${PROMPT}%F{green}\$(strager_prompt_cwd)%f"
# Exit code of previous command.
PROMPT="${PROMPT}%(0?;; %F{red}%?%f)"
# Terminator.
PROMPT="${PROMPT}> "

# => Cursor
_fix_cursor() {
   echo -ne '\e[6 q'
}

precmd_functions+=(_fix_cursor)

# => ls
zstyle ':completion:*' menu select
