source $HOME/dotfiles/zsh/zsh_aliases

export EDITOR=vim
export HISTFILE=~/.zsh_history
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS

# Command interpretation
setopt CHASE_DOTS
setopt INTERACTIVE_COMMENTS
setopt AUTOCD

# Keyboard bindings
bindkey '^I' menu-expand-or-complete

# => Completion
unsetopt auto_remove_slash
zstyle ':completion:*' menu select

source ~/dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
