# Credit to Strager https://github.com/strager/dotfiles/

# Git
alias gs="git status -s -b && git log -n 5 --oneline"
alias gc="git commit -v"
alias g.="git add -p"
alias gi="git add -i"
alias g^="git push"
alias gl="git log --stat"
alias gd="git diff"
alias gfp="git fetch && git pull"

# Shortcut
alias cd.="cd ../"
alias cd..="cd ../../"
alias cd...="cd ../../../"
